config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|vi/ do
    root 'home#index'

    # Devise User
    devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'login', to: 'users/sessions#new'
    end
    resources :users, only: %i[update]
    resources :exams, only: %i[index show]
    resources :user_exams do
      member do
        get :exam_start
      end
    end
    get 'user/profile', to: 'users#edit', as: 'profile'

    # Devise Admin
    devise_for :admins, controllers: { sessions: 'admins/sessions' }
    namespace :admins do
      root 'pages#index'
      resources :users
      resources :categories
      resources :exams
      resources :user_exams, only: %i[index show]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
# frozen_string_literal: true

class Exam < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: :reject_questions, allow_destroy: true
  has_many :user_exams
  # Validate
  validates :content, presence: true

  enum status: %i[draft public], _prefix: true
  scope :check_exam, ->(user) {
    status_public.includes(:user_exams).where( user_exams: {completed: true, user_id: user.id}).ids }
  scope :list_exam, ->(exam_id) { status_public.where.not(id: exam_id) }

  private

  def reject_questions(attributes)
    attributes['content'].blank? || attributes['point'].blank?
  end
end

app/controllers/admins/exams_controller.rb
# frozen_string_literal: true

module Admins
  class ExamsController < BaseController
    before_action :set_exam, only: %i[edit update destroy]
    before_action :current_exam, only: :show

    def index
      @exams = Exam.all.decorate
    end

    def new
      @exam = Exam.new
      question = @exam.questions.build
      question.answers.build
    end

    def create
      @exam = Exam.new exam_params
      if @exam.save
        redirect_to admins_exams_path
      else
        render :new
      end
    end

    def show
      @questions = @exam.questions
    end

    def edit; end

    def update
      if @exam.update_attributes(exam_params)
        redirect_to admins_exams_path
      else
        render :edit
      end
    end

    def destroy
      redirect_to admins_exams_path if @exam.destroy
    end

    private

    def exam_params
      params.require(:exam).permit( :content, :status, :category_id,
                      questions_attributes: [ :id, :content, :point, :_destroy,
                      answers_attributes: [:id, :text, :correct, :_destroy]])
    end

    def set_exam
      @exam = Exam.find_by(id: params[:id])
      return redirect_to(admins_exams_url, alert: "Can't edit this exam!") if @exam.blank? || @exam.status_public?
    end

    def current_exam
      @exam = Exam.find_by(id: params[:id])
      return redirect_to(admins_exams_url, alert: 'Exam is not found!') if @exam.blank?
    end
  end
end

app/controllers/exams_controller.rb
# frozen_string_literal: true

class ExamsController < ApplicationController
  before_action :set_user, only: %i[index]

  def index
    @exams = Exam.list_exam(Exam.check_exam(current_user)).decorate
  end

  private

  def set_user
    @user = current_user.decorate if user_signed_in?
  end
end

app/helpers/exams_helper.rb
# frozen_string_literal: true

module ExamsHelper
  def exams_size
    Exam.all.size
  end

  def answer_correct(answer)
    'list-group-item-success' if answer.correct?
  end
end

app/views/admins/exams/shared/_answer_fields.html.erb
<div class="nested-fields border border-info p-2 container mb-2">
  <div class="form-group ml-3">
    <%= f.text_area :text, class: 'form-control', cols: '20', rows: '4', placeholder: t('.answer') %>
    <div class="d-flex text center justify-content-end mt-2">
      <%= f.select :correct, [[t('.correct'), true], [t('.incorrect'), false]], {}, class: "form-control w-7-em", placeholder: t('.content') %>
      <%= link_to_remove_association t('.remove_answer'), f, class: 'ml-3 btn btn-sm btn-danger' %>
    </div>
  </div>
</div>

app/views/admins/exams/shared/_form.html.erb
<div class="container">
  <%= render 'admins/shared/error_messages', resource: @exam %>
  <%= form_for [:admins, @exam] do |f| %>
    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :content), {}, { class: 'form-control custom-select mb-3'} %>
    <%= f.select :status, options_for_select(Exam.statuses.map{|key, value| [key.humanize, key]}), {}, { class: 'custom-select mb-3'} %>
    <%= f.text_field :content, class: 'form-control mb-3', placeholder: t('.exam_content')%>
    <div class="list_question">
      <div class="form-group question-item border border-secondary p-3 mb-3">
        <%= f.fields_for :questions do |question| %>
          <%= render 'admins/exams/shared/question_fields', f: question %>
        <% end %>
        <div class="text-left">
          <%= link_to_add_association t('.add_question'), f, :questions, partial: 'admins/exams/shared/question_fields', class: 'btn btn-sm btn-primary form control m-2' %>
        </div>
      </div>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admins/exams/shared/_list_exam.html.erb
<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3 d-flex">
      <h6 class="m-0 font-weight-bold text-primary">
        <%= t('.exam', size: exams_size) %> &emsp;
      </h6>
      <h6 class="m-0 font-weight-bold text-primary">
        <i class="fas fa-plus-circle text-primary"></i>
        <%= link_to t('.new_exam'), new_admins_exam_path %>
      </h6>
    </div>
    <div class="card-body">
      <div class="table-responsive-xl">
        <table class="table table-striped text-center w-100 border" cellspacing="0">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= t('.category') %></th>
              <th><%= t('.content') %></th>
              <th><%= t('.status') %></th>
              <th><%= t('.total_question') %></th>
              <th colspan="3"><%= t('.action') %></th>
            </tr>
          </thead>
          <tbody>
            <% @exams.each do |exam| %>
              <tr>
                <td>
                  <%= exam.id %>
                </td>
                <td class="text-info">
                  <%= exam.exam_category %>
                </td>
                <td>
                  <%= exam.content%>
                </td>
                <td class="text-<%= exam.check_exam_status %>">
                  <%= exam.status%>
                </td>
                <td>
                  <%= exam.exam_question_size %>
                </td>
                <td class="w-5">
                  <%= link_to admins_exam_path(exam) do %>
                  <i class="fas fa-eye text-info"></i>
                  <% end %>
                </td>
                <% if exam.status_draft? %>
                  <td class="w-5">
                    <%= link_to edit_admins_exam_path(exam) do %>
                      <i class="far fa-edit text-warning"></i>
                    <% end %>
                  </td>
                  <td class="w-5">
                    <%= link_to admins_exam_path(exam), method: :delete, data: {confirm: 'Are you sure to delete this exam?'} do %>
                      <i class="fas fa-trash text-danger"></i>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admins/exams/shared/_question_fields.html.erb
<div class="nested-fields border border-danger p-2 mb-2">
  <p> <%= t('.question')%> </p>
  <%= f.text_field :content, class: "form-control mb-3", placeholder: t('.content') %>
  <%= f.text_field :point, class: "form-control mb-3", placeholder: t('.point') %>
  <%= f.fields_for :answers do |answer| %>
    <%= render 'admins/exams/shared/answer_fields', f: answer %>
  <% end %>
  <div class="text-left">
    <%= link_to_add_association t('.add_answer'), f, :answers, partial: 'admins/exams/shared/answer_fields', class: 'btn btn-sm btn-primary form control m-2' %>
  </div>
  <div class="text-center">
    <%= link_to_remove_association t('.remove_question'), f, class: 'btn btn-sm btn-danger form control m-2' %>
  </div>
</div>