config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|vi/ do
    root 'home#index'

    # Devise User
    devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'login', to: 'users/sessions#new'
    end
    resources :users, only: %i[update]
    resources :exams, only: %i[index show]
    resources :user_exams do
      member do
        get :exam_start
      end
    end
    get 'user/profile', to: 'users#edit', as: 'profile'

    # Devise Admin
    devise_for :admins, controllers: { sessions: 'admins/sessions' }
    namespace :admins do
      root 'pages#index'
      resources :users
      resources :categories
      resources :exams
      resources :user_exams, only: %i[index show]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :set_user, only: :index
  before_action :authenticate_user!

  def index; end

  private

  def set_user
    @user = current_user.decorate if user_signed_in?
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def check_flash(key)
    key == 'notice' ? 'success ' : 'warning'
  end
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <i class="fas fa-school navbar-brand mx-2 text-info font-size-2em"></i>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to t('.home') , root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t('.list_exam'), exams_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to t('.list_user_exam'), user_exams_path, class: "nav-link"%>
      </li>
    </ul>
    <%= render 'home/language' %>
    <form class="form-inline my-2 mx-3 my-lg-0">
      <% unless current_user %>
        <%= link_to "Login", login_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      <% else %>
        <div class="dropdown">
          <button class="btn btn-out-secondary my-2 my-sm-0 text-info" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
            <%= image_tag @user.default_avatar_user, class: 'rounded-circle img-size-2em' %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <%= link_to t('.setting'), profile_path, class: "dropdown-item" %>
            <%= link_to t('.logout'), destroy_user_session_path, method: :delete, class: "dropdown-item text-danger", data: { confirm: t('.confirm')} %>
          </div>
        </div>
      <% end %>
    </form>
  </div>
</nav>

app/views/home/_language.html.erb
<%= link_to 'En', locale:'en' %>
<%= link_to 'Vi', locale:'vi' %>

app/views/home/index.html.erb
<div class="fixed-bottom d-flex text-center w-50">
  <%= render 'layouts/messages' %>
</div>