config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|vi/ do
    root 'home#index'

    # Devise User
    devise_for :users, controllers: { sessions: 'users/sessions' }
    devise_scope :user do
      get 'login', to: 'users/sessions#new'
    end
    resources :users, only: %i[update]
    resources :exams, only: %i[index show]
    resources :user_exams do
      member do
        get :exam_start
      end
    end
    get 'user/profile', to: 'users#edit', as: 'profile'

    # Devise Admin
    devise_for :admins, controllers: { sessions: 'admins/sessions' }
    namespace :admins do
      root 'pages#index'
      resources :users
      resources :categories
      resources :exams
      resources :user_exams, only: %i[index show]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_exams, dependent: :destroy
  # Attached avatar
  has_one_attached :avatar
  # Validate
  validates :username, presence: true, length: { maximum: 20 }, format: { with: /\A[a-zA-Z0-9]+\z/ },
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :phone, format: { with: /\d[0-9]\)*\z/ }, length: { minimum: 10, maximum: 15 }, allow_nil: true

  ransacker :full_name do |parent|
    Arel::Nodes::NamedFunction.new('CONCAT_WS', [
      Arel::Nodes.build_quoted(' '), parent.table[:first_name], parent.table[:last_name]
    ])
  end
end

app/controllers/admins/users_controller.rb
# frozen_string_literal: true

module Admins
  class UsersController < BaseController
    before_action :set_user, only: %i[edit update destroy]

    def index
      @q = User.ransack(params[:q])
      @users = @q.result.decorate
    end

    def new
      @user = User.new
    end

    def edit; end

    def create
      @user = User.new user_params
      if @user.save
        redirect_to admins_users_path
      else
        render :new
      end
    end

    def update
      if @user.update_attributes(user_params)
        redirect_to admins_users_path
      else
        render :edit
      end
    end

    def destroy
      return redirect_to admins_users_path if @user.destroy
    end

    private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find_by(id: params[:id])
      return redirect_to(admins_users_url, alert: 'User not exit') if @user.blank?
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update]
  before_action :set_user

  def edit; end

  def update
    if current_user.update(user_params)
      bypass_sign_in(current_user)
      flash[:notice] = 'Profile updated'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    update_attrs = %i[username avatar first_name last_name phone password password_confirmation]
    params.require(:user).permit(update_attrs)
  end

  def set_user
    @user = current_user.decorate
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def regex_name_validate
    Settings.regex_name_vn
  end

  def users_size
    User.all.size
  end
end

app/views/admins/users/shared/_form.html.erb
<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3"> 
      <%= link_to t('.back'), admins_users_path, class: "m-0 font-weight-light text-primary" %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <%= form_for [:admins, @user] do |f| %>
          <div class="d-flex justify-content-center">
            <div class="form-group text-muted w-50 ">
              <%= render "admins/shared/messages" %>
              <%= f.text_field :email, class: "form-control mb-3", placeholder: "Email", required: true %>
              <%= f.text_field :username, class: "form-control mb-3", placeholder: "Username", required: true %>
              <%= f.password_field :password, class: "form-control mb-3", placeholder: "Password", required: true %>
            </div>
          </div>
          <div class="text-right">
            <%= f.submit class: "btn btn-primary" %>
          </div>  
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/shared/_list_user.html.erb
<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3 d-flex">
      <h6 class="m-0 font-weight-bold text-primary">
        <%= t('.users_size', size: users_size) %>
      </h6>
      <h6 class="m-0 font-weight-bold text-primary ml-2">
        <i class="fas fa-plus-circle text-primary"></i>
        <%= link_to t('.new_user'), new_admins_user_path %>
      </h6>
    </div>
    <%= render 'admins/users/shared/search' %>
    <div class="card-body">
      <div class="table-responsive-xl">
        <% if @users.present? %>
          <div class='text-success ml-4'>
            <i class="fas fa-globe-europe"></i>: 
            <%= t('.results', users_size: @users.size) %>
          </div>
          <table class="table table-striped text-center w-100" id="table-tag" cellspacing="0">
            <thead>
              <tr>
                <th>
                  ID
                </th>
                <th>
                  <%= t('.avatar') %>
                </th>
                <th>
                  <%= t('.user_name') %>
                </th>
                <th>
                  <%= t('.full_name') %>
                </th>
                <th>
                  <%= t('.phone') %>
                </th>
                <th colspan="2">
                  <%= t('.action') %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= user.id %>
                  </td>
                  <td>
                    <%= image_tag user.default_avatar_user, class: "img-size-2em" %>
                  </td>
                  <td class="text-info">
                    <%= user.username %>
                  </td>
                  <td>
                    <%= user.full_name %>
                  </td>
                  <td>
                    <%= user.phone %>
                  </td>
                  <td>
                    <%= link_to edit_admins_user_path(user) do %>
                      <i class="far fa-edit text-warning"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to admins_user_path(user), method: :delete, data: {confirm: t('.confirm') } do %>
                      <i class="fas fa-trash text-danger"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class='text-center text-muted'>
            <i class="far fa-ques tion-circle"></i>
            <%= t('.no_result_html') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/shared/_search.html.erb
<div class="card-header py-3 d-flex w-100">
  <%= search_form_for [:admins, @q], class: "w-100" do |f| %>
    <div class="form-group w-50 float-left">
      <div class="input-group mb-3">
        <%= f.text_field :username_or_full_name_cont, class: "form-control", placeholder: t('.search_placeholder') %>
        <div class="input-group-append ml-2">
          <%= f.submit t('.search'), class: "btn btn-secondary btn-sm" %>
        </div>
      </div>
    </div>
  <% end %>
</div>